### ISSUE TITLE
[Feature] support to cleanup external resources after pods/workload terminated

### ISSUE THREAD

**Issue by skyrise-l** [apecloud/kubeblocks-addons#666]
**Describe the bug**
In the PostgreSQL addon, after adding the etcd service, it is not possible to delete the configuration records in etcd when removing the PostgreSQL addon through methods like preTerminate (deleting them will cause them to be restored). There might need to be a "postTerminate" to perform the deletion after the container has terminated normally.

**Comment by nayutah** [comment]
@leon-inf What are expected behaviors of kubeblocks operator when 'PreTerminate' action fails or timeouts ?

**Comment by leon-inf** [comment]
> @leon-inf What are expected behaviors of kubeblocks operator when 'PreTerminate' action fails or timeouts ?

It will retry and wait until the action completes successfully.

**Comment by leon-inf** [comment]
@Y-Rookie is already working on this requirement.

**Comment by Y-Rookie** [comment]
Current problem：

In the PreTerminate action, we need to stop the PG Patroni process, and currently, this is done by executing the pkill command through kubectl exec to log into the engine pod. However, kubectl depends on RBAC permissions. In the default implementation of PreTerminate, a job was used to perform the action, but the required RBAC configuration for executing the job is not exposed via the API. Additionally, the default service account on the engine pod is deleted by the cluster controller before the PreTerminate action is executed (due to compatibility reasons, it is deleted by the cluster controller instead of the component controller) so we could not use it, resulting in a lack of RBAC permissions which prevents execution.
